# Generated by Django 4.0.4 on 2022-05-24 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_t', models.CharField(max_length=20, verbose_name='Тип мероприятия')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_s', models.CharField(max_length=30, verbose_name='Специализация')),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_u', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname_u', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('link', models.CharField(max_length=30, verbose_name='Связь со мной')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.skills', verbose_name='Специализация')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_e', models.CharField(max_length=20, verbose_name='Название мероприятия')),
                ('about', models.TextField(blank=True, verbose_name='Описание')),
                ('time', models.DateTimeField(verbose_name='Время проведения')),
                ('is_ok', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('evtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.evtype', verbose_name='Тип мероприятия')),
            ],
        ),
    ]
